
# 示例字典数据
products = [
    {
        'csv': [None, None, None, [0, -1], [3342962, 3498], None, None, None, None, None, None, None, None, None, None,
                None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
        'categories': None,
        'imagesCSV': '41uH%2B5hN7uL.jpg',
        'manufacturer': None,
        'title': None,
        'lastUpdate': 5535096,
        'lastPriceChange': 0,
        'rootCategory': 9223372036854775807,
        'productType': 3,
        'parentAsin': 'B01LZNR7JT',
        'variationCSV': 'B0039GEK6C,B0039GCRAI,B0039GCR30,B0039GEK58',
        'asin': 'B0039GEK6C',
        'domainId': 1,
        'type': None,
        'hasReviews': True,
        'trackingSince': 0,
        'brand': None,
        'productGroup': None,
        'partNumber': None,
        'model': None,
        'color': None,
        'size': None,
        'edition': None,
        'format': None,
        'packageHeight': 0,
        'packageLength': 0,
        'packageWidth': 0,
        'packageWeight': 0,
        'packageQuantity': -1,
        'isAdultProduct': False,
        'isEligibleForTradeIn': False,
        'isEligibleForSuperSaverShipping': False,
        'offers': None,
        'buyBoxSellerIdHistory': None,
        'isRedirectASIN': False,
        'isSNS': True,
        'author': None,
        'binding': None,
        'numberOfItems': 0,
        'numberOfPages': 0,
        'publicationDate': -1,
        'releaseDate': -1,
        'languages': None,
        'lastRatingUpdate': 3551180,
        'ebayListingIds': None,
        'lastEbayUpdate': 0,
        'eanList': None,
        'upcList': None,
        'liveOffersOrder': None,
        'frequentlyBoughtTogether': ['B0002568YK'],
        'features': None,
        'description': None,
        'promotions': None,
        'newPriceIsMAP': False,
        'coupon': None,
        'availabilityAmazon': -1,
        'listedSince': 0,
        'fbaFees': None,
        'variations': [
            {'asin': 'B0039GEK6C', 'attributes': [{'dimension': 'Size', 'value': '1.1-Pound'}]},
            {'asin': 'B0039GCRAI', 'attributes': [{'dimension': 'Size', 'value': '3.2-kg / 7-lb'}]},
            {'asin': 'B0039GCR30', 'attributes': [{'dimension': 'Size', 'value': '125-g / 4.4-oz'}]},
            {'asin': 'B0039GEK58', 'attributes': [{'dimension': 'Size', 'value': '250-g / 8.8-oz'}]}
        ],
        'itemHeight': -1,
        'itemLength': -1,
        'itemWidth': -1,
        'itemWeight': -1,
        'salesRankReference': -1,
        'salesRanks': None,
        'salesRankReferenceHistory': None,
        'launchpad': False,
        'isB2B': False,
        'stats': None,
        'offersSuccessful': False,
        'g': 2405,
        'categoryTree': None,
        'data': {
            'SALES_time': (['2011-01-01']),
            'SALES': [-1],
            'df_SALES': [{'value': -1}]
        }
    }
]
